//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GaiaMovement.Models
{
    using System;
    using System.Collections.Generic;

    public partial class PosAndVelJSON
    {
        public string PosAndVelJSONString { get; set; }
    }
    public partial class Smaller
    {
        public int ID { get; set; }
        public Nullable<float> px { get; set; }
        public Nullable<float> py { get; set; }
        public Nullable<float> pz { get; set; }
        public Nullable<float> vx { get; set; }
        public Nullable<float> vy { get; set; }
        public Nullable<float> vz { get; set; }
        public Nullable<float> V { get; set; }
    }
}
